### ISSUE TITLE
support for no-color

### ISSUE THREAD

**Issue by tgfjt** [davidtheclark/postcss-log-warnings#14]
Hi!
I'm just trying https://github.com/stylelint/stylelint/issues/15

Do you have any plan to log with no-color for disable colored output?

It seems to be good for running stylelint task on Jenkins (is not support ANSI, and can't install ANSIcolor-plugin:sob:)
(also on cmd.exe...)

IMO, the linter tools are often executed on CI for production environment.

**Comment by davidtheclark** [comment]
Agreed. This should be an option.

**Comment by davidtheclark** [comment]
Just learned that because this uses the `chalk` library you should be able to specify no colors simply by adding `--no-colors` to your command. Does that work for you?

**Comment by tgfjt** [comment]
Oh, Thanks. Yes It works fine with `--no-colors`!
