### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by ai** [davidtheclark/postcss-log-warnings#2]
Maybe we need a screenshot to show awesome chulk output?

**Comment by davidtheclark** [comment]
I thought that would be a good idea, too.

Do you know if any plugins out there are already all hooked up with the warnings API so that I can use them instead of fake plugins in the example? Or I guess I could use this as an excuse to update my couple of plugins ...

**Comment by ai** [comment]
Nope :). I plan add to Autoprefixer, but it will only in the end of April.

@MoOx @yisibl are you have a plans for warnings API?
