### ISSUE TITLE
"warnings were found" but not shown

### ISSUE THREAD

**Issue by VinSpee** [davidtheclark/postcss-log-warnings#5]
Hi!

I'm using postcss-log-warnings in tandem with postcss-bem-linter. My setup is as follows:

``` js
gulp.task('styles:toolkit', function () {
  var sourcemaps = require('gulp-sourcemaps');
  var postcss = require('gulp-postcss');
  var bem_linter = require('postcss-bem-linter');
  var calc = require('postcss-calc');
  var colorFunction = require('postcss-color-function');
  var customMedia = require('postcss-custom-media');
  var customProperties = require('postcss-custom-properties');
  var fontVariant = require('postcss-font-variant');
  var lost = require('lost');
  var inline = require('postcss-import');
  var nested = require('postcss-nested');
  var simpleVars = require('postcss-simple-vars');
  var plumber = require('gulp-plumber');
  var logWarnings = require('postcss-log-warnings');
  var processors = [
    inline(),
    nested,
    bem_linter('suit', { namespace: 'l11' }),
    customProperties(),
    calc(),
    simpleVars(),
    customMedia(),
    lost(),
    colorFunction(),
    fontVariant(),
    logWarnings({throwError: true})
  ];
  return gulp.src(config.src.styles.toolkit)
    .pipe(sourcemaps.init())
    .pipe(plumber())
    .pipe(postcss(processors))
    .pipe(prefix())
    .pipe(sourcemaps.write())
    .pipe(gulpif(!config.dev, csso()))
    .pipe(gulp.dest(config.dest + '/assets/toolkit/styles'))
    .pipe(gulpif(config.dev, reload({stream:true})))
});
```

when running (with an intentional bem-linter error), i get the following output:

``` bash
> gulp styles:toolkit
[11:22:31] Using gulpfile ~/projects/LevelEleven/ui-kit/gulpfile.js
[11:22:31] Starting 'styles:toolkit'...
[11:22:32] Finished 'styles:toolkit' after 1.23 s

** postcss-log-warnings: warnings were found **
```

the errors aren't shown. Any idea what's wrong with my setup?

Thanks!

**Comment by davidtheclark** [comment]
Have you tried eliminating parts of this build to see if a specific tool might be causing the weirdness? I'm wondering what will happen if you try to reduce this to a more straightforward procedure. Lots of things _could_ be going wrong here, which may or may not have to do with bem-linter or log-warnings.

Another debugging strategy to try is to run the same processors with straight postcss, instead of postcss-gulp, and make sure you catch and print errors. I've had a couple of problems in the past with postcss-gulp silently swallowing errors.

(Also, is `prefix()` defined outside of the scope of what you pasted? I'm not seeing it.)

**Comment by VinSpee** [comment]
yes, it is defined outside (gulp-autoprefixer, lost grid doesn't play nicely with it for some reason). I'll try reducing my use case.

**Comment by davidtheclark** [comment]
Another possibility: what version of bem-linter are you using? The documentation on Github reflects the master branch which has not yet had an npm release. So unless you are using the master branch those options you're passing to bem-linter might be breaking the process.

**Comment by VinSpee** [comment]
That's the ticket. Thanks!

**Comment by davidtheclark** [comment]
Hopefully an npm release of postcss-bem-linter will be out soon with those new features. cc/ @necolas

**Comment by davidtheclark** [comment]
Turns out this probably is a problem with the plugin, @VinSpee : #6

**Comment by VinSpee** [comment]
Awesome, I'll try this as soon as I'm back on the grid.
